name: "govulncheck"

on:
  push:
    branches: [ "main", "next" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "next" ]
  schedule:
    - cron: '29 21 * * 6'

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          # Use the latest available Go version, and disable the cache
          # (because it often interferes with finding it).
          # This helps reduce false positives when there are security issues
          # in the Go distribution itself.
          go-version-input: 'stable'
          check-latest: true
          cache: false
